### ISSUE TITLE
Checkpoint 1 

### ISSUE THREAD

**Issue by kailynangelo** [kailynangelo/nbaStatsFun#2]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @kailynangelo! Thanks for your patience around getting feedback on this. I normally like to turn things around much quicker than 1 week.  

I'm really looking forward to your work on this and supporting you along the way! I'm particularly interested in those random stats options! Following are my observations from a review of checkpoint 1. If you have any questions about my comments or anything else, please ask.

**Problem statement** provides a clear explanation of the problem your app will solve. 

Improvement ideas: 

- [ ] You mentioned cluttered, ads, and difficulty navigating. It would really sell app idea if your website description addressed those issues. Perhaps something about clean or minimalist design, no ads, navigation built with the user in mind, etc. 
- [ ] You could included the tech you plan to use, including the  targeted service/api. This is helpful for those reviewing the repository (prospective employers, maybe?!)

**User Stories** these clearly identify what the application will do and include functionality to meet many of the requirements of the course, such as multiple one to many relationships, and create, read, and update capabilities. What you've selected for mvp feels  doable in the semester!

Improvement ideas:

- [ ] small typo here, I think, player refers to team? https://github.com/kailynangelo/nbaStatsFun/blob/main/DesignDocuments/UserStories.md#player-lookup
- [x] I did not see a story that meets the delete requirement of the project. Is there something you could include that might help you demonstrate that? Maybe Remove Favorite team could be mvp?

**Project plan** is off to a good start with a good level of detail in week 4 and 5. A good next step here may be to identify which user story you would like to work on first, and think about what pieces you need to finish that story. Then repeat! 

**Screen Design** I didn't find this. ScreenDesign.md was empty (0 bytes) when I looked at it on GitHub.  One thing I look for when reviewing screens is that all MVP user stories are represented.

**WeeklyRecap** Off to a good start with this too - clearly documents what you did and how long it took!
